name: Release new action version
on:
  release:
    types: [released]

permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Add target
      run: rustup target add wasm32-unknown-unknown
    - name: Build & compile
      run: cargo build --target wasm32-unknown-unknown --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/wasm32-unknown-unknown/release/flb_filter_iis_wasm.wasm
        asset_name: flb_filter_iis_wasm.wasm
        tag: ${{ github.ref }}
        overwrite: true
        body: "New Release"
    # - name: Upload artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Binary
    #     path: |
    #       target/wasm32-unknown-unknown/release/flb_filter_iis_wasm.wasm
